exp_dir: tmp2

drl:
  class: PPO
  config:
    lr_schedule: [[0, 3.0e-4], [4000000, 3.0e-9]]
    # rollout_fragment_length: 2048
    # sgd_minibatch_size: 64
    # num_sgd_iter: 10
    lambda: 0.95
    vf_loss_coeff: 0.5
    vf_clip_param: 0.2
    clip_param: 0.2
    grad_clip: 0.5
    env: SwimmerWithBoundsClassic
    env_config:
      reset_on_bounds: False
      # noise: [0.10, 0.18, 0.18, 0.065, 0.20, 0.20, 0.41, 0.41]
    framework: torch
    evaluation_config:
      env_config:
        # noise: [0.10, 0.18, 0.18, 0.065, 0.20, 0.20, 0.41, 0.41]
        reset_on_bounds: False
        explore: False
    evaluation_interval: 1
    evaluation_duration: 10

ray_config:
    run_config:
        name: "test_swimmer_baseline_no_reset_no_noise_cleanRL"
        stop:
            # timesteps_total
            num_env_steps_sampled: 4.0e+6
        log_to_file: True 
    tune_config:
        num_samples: 20 # number of sample trials to run
    checkpoint_freq: 50