n_train_iter: 6000
dyn_fit_freq: 10
exp_dir: tmp2

# used for rolling out new on-policy data for 
# dynamics fitting
real_env:
  class: DMCEnvWrapper
  config: 
      domain_name: "cartpole"
      task_name: "swingup"
      from_pixels: False
      task_kwargs:

drl:
  class: PPO
  config:
    env: 
    env_config:
      max_episode_steps: 300
      real_env_class: DMCEnvWrapper
      real_env_config: 
        domain_name: "cartpole"
        task_name: "swingup"
        from_pixels: False
        task_kwargs:
      init_real_on_start: True
      use_real_env: False
      ensemble_mode: median
      init_weights: True
      act_dim: 1
      obs_dim: 5
      act_bounds: 
        - [-1, 1]
      obs_bounds: 
        - [-5, 5] # pos
        - [-1.1, 1.1] # cos(th)
        - [-1.1, 1.1] # sin(th)
        - [-10, 10] # dx
        - [-10, 10] # dth

    framework: torch

    evaluation_config:
      env_config:
        init_real_on_start: True
        use_real_env: True
        use_bounds: False
        real_env_class: DMCEnvWrapper
        real_env_config: 
          domain_name: "cartpole"
          task_name: "swingup"
          from_pixels: False
          task_kwargs:
      explore: False
    evaluation_interval: 1
    evaluation_duration: 5


off_policy_buffer:
  config:
    max_traj:
    max_samples:
  init: 
    type: collect
    kwargs: 
      n_steps: 4000 # 12000
      n_steps_reset: 500
      # seed: 0 # TO-DO: set seed in dmc env

on_policy_buffer:
  config:
    max_traj: 
    max_samples: 4000 # 12000
  collect:
    n_steps: 500
    n_steps_reset: 1000

dynamics_model:
  'callbacks': project_cartpole
  'dt': 1
  'discrete': True 
  'optimizer': 
    'base_optimizer':
      'name': 'STLSQ'
      'kwargs': 
        'alpha': 5.0e-5
        'threshold': 7.0e-3
    'ensemble':
      'bagging': True
      'library_ensemble': True
      'n_models': 100
  'feature_library': 
    name: affine
    kwargs:
      poly_deg: 2
      n_state: 5 
      n_control: 1
      poly_int: True
      tensor: True
    
rew_model:
  'use_control': True
  'optimizer': 
    'base_optimizer':
      'name': 'STLSQ'
      'kwargs': 
        'alpha': 1.0e-5
        'threshold': 5.0e-2
    'ensemble':
      'bagging': True
      'library_ensemble': True
      'n_models': 100
  'feature_library': 
    name: PolynomialLibrary
    kwargs:
      degree: 2
      include_bias: False
      include_interaction: True

ray_config:
    run_config:
        name: "test_dyna_dmc-cartpole_10_300len_4k"
        stop:
            # timesteps_total
            num_env_steps_sampled: 2.4e+6
        log_to_file: True 
    tune_config:
        num_samples: 20 # number of sample trials to run
    checkpoint_freq: 50