exp_dir: tmp2

drl:
  class: PPO
  config:
    lr_schedule: [[0, 3.0e-4], [10000000, 3.0e-9]]
    # rollout_fragment_length: 2048
    # sgd_minibatch_size: 64
    # num_sgd_iter: 10
    lambda: 0.95
    vf_loss_coeff: 0.5
    vf_clip_param: 0.2
    clip_param: 0.2
    grad_clip: 0.5
    env: DMCEnvWrapper
    env_config:
      domain_name: "cartpole"
      task_name: "swingup"
      from_pixels: False
      frame_skip: 1
      task_kwargs: 
    framework: torch
    evaluation_config:
      domain_name: "cartpole"
      task_name: "swingup"
      from_pixels: False
      task_kwargs: 
    evaluation_interval: 1
    evaluation_duration: 5

ray_config:
    run_config:
        name: "test_cartpole_baseline_eval_fc=64_cleanRL_loss_params_long_checkpoints"
        stop:
            # timesteps_total
            num_env_steps_sampled: 1.0e+7
        log_to_file: True 
    tune_config:
        num_samples: 20 # number of sample trials to run
    checkpoint_freq: 50