exp_dir: cylinder_baseline
fcnet_hiddens: [64, 64]
# use_pbt: True

drl:
  class: PPO
  config:
    rollouts: {}
        # rollout_fragment_length: 10
    training:
      # train_batch_size: 20
      # sgd_minibatch_size: 5
      
      lr_schedule: [[0, 3.0e-4], [2000000, 3.0e-9]]
      # lr: 3.0e-4
      lambda_: 0.95
      vf_loss_coeff: 0.5
      vf_clip_param: 0.2
      clip_param: 0.2
      grad_clip: 0.5
    environment:
      env: CylinderWrapper
      env_config: 
          hydro_config:
            flow_config:
              actuator_integration: 'implicit'
              Re: 100
              mesh: medium
              restart: '/home/firedrake/sindy-rl/data/hydro/cylinder/2023-12-13_medium/Re=100_dt=1e-3/snapshots/no_control_487500.ckpt'
            solver_config:
                dt: 1.0e-2
          n_skip_on_reset: 5
          control_freq: 10
          max_episode_steps: 200
    framework: torch
    evaluation: {}
    #   evaluation_config:
    #     env_config:
    #       domain_name: "cartpole"
    #       task_name: "swingup"
    #       from_pixels: False
    #       task_kwargs: 
    #         time_limit: 3 # DEFAULT IS 10!
    #   evaluation_interval: 1
    #   evaluation_duration: 5
    #   evaluation_duration_unit: "episodes"
    #   always_attach_evaluation_results: True

ray_config:
    run_config:
        name: "baseline_4k"
        stop:
            # timesteps_total
            num_env_steps_sampled: 5.0e+6
        log_to_file: True 
    tune_config:
        num_samples: 20 # number of sample trials to run
    checkpoint_freq: 1