# DRL Algo config
drl_config: 
    environment:
        env: SwimmerSurrogate
        env_config:
            dyn_model: null # None
            max_episode_steps: 1000
            mod_angles: True
            reset_on_bounds: True
    framework: 
        framework: torch
    evaluation:
        evaluation_config:
            env_config:
                dyn_model: null # None
                max_episode_steps: 1000
                mod_angles: True
                reset_on_bounds: True
            explore: False
        evaluation_interval: 1


# Ray Configs
ray_config:
    run_config:
        stop: 
            "training_iteration": 300
    tune_config:
        num_samples: 20
    checkpoint_freq: 10


# SINDy Configs
init_collection:
    collect_seed: 0 
    n_random_steps: 4000
    n_null_steps: 8000
    max_traj_len: 100

dyn_model_config:
    affine_config: 
        poly_deg: 2 
        n_state: 8 
        n_control: 2
        poly_int: False
        tensor: True
    base_config:
        threshold: 0.02 
        alpha: 0.5
    ensemble_config:
        bagging: True 
        library_ensemble: True
        n_models: 100

baseline: True